name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # or main depending on your branch name
  pull_request:
    branches:
      - master  # or main depending on your branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2  # Use v2 as v3 might not be available
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run tests
      run: mvn clean test

    - name: Upload test reports as artifacts
      uses: actions/upload-artifact@v2  # Use v2 for upload-artifact action
      with:
        name: surefire-reports
        path: target/surefire-reports/

    - name: Upload ExtentReports as artifact
      uses: actions/upload-artifact@v2  # Use v2 for upload-artifact action
      with:
        name: extent-reports
        path: target/extent-report/ExtentReport.html
