name: Run Maven Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Initial cleanup
      - name: Clean previous test artifacts
        run: |
          echo "Cleaning previous test outputs..."
          sudo rm -rf test-output/ || true
          sudo rm -rf target/surefire-reports/ || true
          mkdir -p test-output target/surefire-reports
          sudo chmod -R 777 test-output target

      # Set up environment
      - name: Setup environment
        run: |
          sudo chmod -R 777 .
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          echo "Chrome version: $(google-chrome --version)"
          sudo rm -rf /tmp/.com.google.Chrome* || true
          sudo rm -rf /tmp/chrome-profile* || true
          pkill -9 -f chrome || true
          pkill -9 -f chromedriver || true

      - name: Verify test resources
        run: |
          mkdir -p resources
          if [ -f "resources/testdata.xlsx" ]; then
            echo "Test data verified"
            ls -la resources/testdata.xlsx
          else
            echo "::error::Test data file missing!"
            exit 1
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            target/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Execute all tests
        run: |
          # Force clean report directories
          rm -rf test-output/* || true
          rm -rf target/surefire-reports/* || true
          
          # Run all tests in MagentoTest class
          mvn clean test \
            -Dtest=tests.MagentoTest \
            -Dmaven.test.failure.ignore=true \
            -DargLine="-Djava.awt.headless=true" \
            -e -X
            
          # Verify reports
          echo "--- Generated Reports ---"
          find test-output/ -type f
          find target/surefire-reports/ -type f

      - name: Process test results
        if: always()
        run: |
          if [ -f "target/surefire-reports/TEST-tests.MagentoTest.xml" ]; then
            echo "--- Test Results ---"
            cat target/surefire-reports/TEST-tests.MagentoTest.txt || echo "No text report found"
          fi
          
          if ls test-output/ExtentReport*.html 1> /dev/null 2>&1; then
            echo "Extent Reports:"
            ls -la test-output/ExtentReport*.html
          else
            echo "::warning::No Extent Reports generated!"
          fi

      - name: Post-execution cleanup
        if: always()
        run: |
          pkill -9 -f chrome || true
          pkill -9 -f chromedriver || true
          sudo rm -rf /tmp/.com.google.Chrome* || true
          sudo rm -rf /tmp/chrome-profile* || true

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-${{ github.run_number }}
          path: |
            target/surefire-reports/
            test-output/
          retention-days: 3

      - name: Upload extent report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report-${{ github.run_number }}
          path: test-output/ExtentReport*.html
          retention-days: 3