name: Run Maven Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Prepare test-output folder
        run: mkdir -p test-output && chmod -R 777 test-output

      - name: Build with Maven
        run: mvn clean compile

      - name: Run MagentoTest with debug
        run: mvn -Dtest=tests.MagentoTest test -e -X

      - name: Debug project structure
        run: |
          ls -R
          pwd

      - name: Check Extent Report Content
        if: always()
        run: |
          ls -la test-output/
          cat test-output/*.html || echo "No HTML report found"

      - name: Upload Extent HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-html-report
          path: test-output/  